/* eslint-disable */
// THIS FILE IS AUTO-GENERATED BY graphql-codegen. DO NOT EDIT MANUALLY.
// Run `npm run codegen` to regenerate after schema changes.

export type Maybe<T> = T | null
export type InputMaybe<T> = Maybe<T>
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }

// ─── Scalar types ────────────────────────────────────────────────────────────
export type Scalars = {
  ID: { input: string; output: string }
  String: { input: string; output: string }
  Boolean: { input: boolean; output: boolean }
  Int: { input: number; output: number }
  Float: { input: number; output: number }
  JSON: { input: unknown; output: unknown }
  Date: { input: string; output: string }
  DateTime: { input: string; output: string }
}

// ─── Sanity image types ───────────────────────────────────────────────────────
export type SanityImageDimensions = {
  width: number
  height: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  dimensions: SanityImageDimensions
  lqip?: Maybe<string>
}

export type SanityImageAsset = {
  _id: string
  url: string
  metadata?: Maybe<SanityImageMetadata>
}

export type SanityImageHotspot = {
  x?: Maybe<number>
  y?: Maybe<number>
}

export type SanityImage = {
  asset?: Maybe<SanityImageAsset>
  alt?: Maybe<string>
  hotspot?: Maybe<SanityImageHotspot>
}

// ─── Block types ─────────────────────────────────────────────────────────────
export type Cta = {
  label?: Maybe<string>
  href?: Maybe<string>
}

export type HeroBlock = {
  _type: 'heroBlock'
  _key: string
  title: string
  subtitle?: Maybe<string>
  image?: Maybe<SanityImage>
  cta?: Maybe<Cta>
}

export type RichTextBlock = {
  _type: 'richTextBlock'
  _key: string
  contentRaw?: Maybe<Scalars['JSON']['output']>
}

export type Feature = {
  _key: string
  icon?: Maybe<string>
  title: string
  description?: Maybe<string>
}

export type FeatureGridBlock = {
  _type: 'featureGridBlock'
  _key: string
  heading?: Maybe<string>
  features?: Maybe<Feature[]>
}

export type TestimonialItem = {
  _key: string
  quote: string
  author: string
  role?: Maybe<string>
  avatar?: Maybe<SanityImage>
}

export type TestimonialsBlock = {
  _type: 'testimonialsBlock'
  _key: string
  heading?: Maybe<string>
  testimonials?: Maybe<TestimonialItem[]>
}

export type CallToActionBlock = {
  _type: 'callToActionBlock'
  _key: string
  heading: string
  subheading?: Maybe<string>
  buttonLabel: string
  buttonHref?: Maybe<string>
  backgroundColor?: Maybe<string>
  textColor?: Maybe<string>
}

export type StatItem = {
  _key: string
  value: string
  label: string
  description?: Maybe<string>
}

export type StatsBlock = {
  _type: 'statsBlock'
  _key: string
  heading?: Maybe<string>
  stats?: Maybe<StatItem[]>
}

export type PageBlock =
  | HeroBlock
  | RichTextBlock
  | FeatureGridBlock
  | TestimonialsBlock
  | CallToActionBlock
  | StatsBlock

// ─── Page type ────────────────────────────────────────────────────────────────
export type Slug = {
  current: string
}

export type Page = {
  _id: string
  title: string
  slug: Slug
  seoDescription?: Maybe<string>
  blocks?: Maybe<PageBlock[]>
}

// ─── Query types ─────────────────────────────────────────────────────────────
export type GetPageBySlugQueryVariables = Exact<{ slug: Scalars['String']['input'] }>

export type GetPageBySlugQuery = {
  allPage: Array<Page>
}

export type GetAllPageSlugsQuery = {
  allPage: Array<{ slug: Slug }>
}

// ─── Fragment types (mirrors gql fragments) ──────────────────────────────────
export type HeroBlockFieldsFragment = HeroBlock
export type RichTextBlockFieldsFragment = RichTextBlock
export type FeatureGridBlockFieldsFragment = FeatureGridBlock
export type TestimonialsBlockFieldsFragment = TestimonialsBlock
export type CallToActionBlockFieldsFragment = CallToActionBlock
export type StatsBlockFieldsFragment = StatsBlock
